workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      vars:
        ANDROID_NDK: "25.2.9519653"
      java: 17
    scripts:
      - name: Build APK
        script: |
          # अगर ज़िप फ़ाइल के अंदर कोई फ़ोल्डर है तो उसके अंदर जाओ
          cd $(find . -maxdepth 2 -name "AndroidManifest.xml" -print -quit | sed 's/\/app\/src\/main\/AndroidManifest.xml//' | sed 's/\/src\/main\/AndroidManifest.xml//') 2>/dev/null || true
          
          # गायब बिल्ड फ़ाइलें खुद से बनाना
          if [ ! -f "gradlew" ]; then
            gradle wrapper
          fi
          
          # सेटिंग्स फ़ाइल बनाना
          if [ ! -f "settings.gradle" ]; then
            echo "include ':app'" > settings.gradle
          fi
          
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - "**/build/outputs/apk/**/*.apk"
